export { default as CourseAdd } from "./CourseAdd"
export { default as Home } from "./Home"
export { default as About } from "./About"
export { default as AllCourses } from "./AllCourses"
export { default as SingleCourse } from "./SingleCourse"
export { default as CreateCourse } from "./CreateCourse"
export { default as Competition } from "./Competition"